# Set the Kubernetes context
  - name: Set context cluster
    command: kubectl config set-cluster exo --server=https://{{ master_node.default_ip }}:443 --insecure-skip-tls-verify=true
    tags: ctx

  - name: Set context user
    command: kubectl config set-credentials exo --username={{ k8s_username }} --password={{ k8s_password }}
    tags: ctx

  - name: Create context
    command: kubectl config set-context exo --cluster=exo --user=exo
    tags: ctx

  - name: Use context
    command: kubectl config use-context exo
    tags: ctx
